### ISSUE TITLE
Loading config causes clickgui to have invisible buttons because of the ClickGuiExpanded boolean

### ISSUE THREAD

**Issue by Floofy-Fox** [NathanKassab/SpicyClient#1]
When this happens you will be able to interact with the clickgui buttons but not be able to see them. I recommend also bug testing the tabgui booleans and code to so you can make sure there are no issues with it either

Just change the ClickGuiExpanded boolean to false on all the modules when you load them from the config

**Comment by NathanKassab** [comment]
Will do it tomorrow

**Comment by NathanKassab** [comment]
I fixed it
