### ISSUE TITLE
watchdogban

### ISSUE THREAD

**Issue by Matrix-CN** [NathanKassab/SpicyClient#11]
killaura ban
fly ban
targetstrafe ban
speed ban
badddddd:(

**Comment by NathanKassab** [comment]
I was on yesterday and none of those banned, are you using the latest beta version?

**Comment by Matrix-CN** [comment]
yes

**Comment by Matrix-CN** [comment]
can you give me you config?

**Comment by NathanKassab** [comment]
After some more testing it turned out that blockfly rots were patched so we are currently fixing them

**Comment by Matrix-CN** [comment]
ok
