### ISSUE TITLE
This is illegal.

### ISSUE THREAD

**Issue by MatthewTGM** [NathanKassab/SpicyClient#13]
1. You're not allowed to distribute the Minecraft source
2. You followed an outdated tutorial
3. The client is dogshit lol

**Comment by 0w-alt** [comment]
1. That literally doesn't matter, pretty much every hypixel client illegally distributes the minecraft source illegally, literally nobody cares.
2. It doesn't matter how old the tutorial is, it works, and that's all that matters
3. @NathanKassab has had a fried motherboard for the past 2 weeks, I'm too dumb to code bypasses for it, and everyone else involved in this repo presumably can't be bothered, or are busy/like me.

**Comment by NathanKassab** [comment]
MatthewTGM, I understand that you are mad that you got hacked on in block game but please keep the github issue section related to real issues
