### ISSUE TITLE
List of things to add

### ISSUE THREAD

**Issue by NathanKassab** [NathanKassab/SpicyClient#5]
just some notes

Killaura target hud
Nametags
System to create custom hacks in-game
Better hypixel bhop
breadcrumbs
improve hypixel blink fly
Create hypixel bypassing interact autoblock
Add support for the youtube API t be able to watch videos in the client while playing the game
Criticals module
Wtap module
hypixel bypassing blockfly

**Comment by KtntKot** [comment]
if(MiniTarget.isEnabled())
			{
				offset = 35;
			}else
			{
				offset = 0;
			}
			
			Gui.drawRect((GuiScreen.width/1.8f - 5 - offset), (GuiScreen.height/1.5f - 5), (GuiScreen.width/1.8f)+ 120, (GuiScreen.height/1.5f)+40, new Color(0, 0, 0, 140).getRGB());
			Gui.drawRect((GuiScreen.width/1.8f - 6 - offset), (GuiScreen.height/1.5f - 6), (GuiScreen.width/1.8f)+ 121, (GuiScreen.height/1.5f)+41, new Color(0, 0, 0, 110).getRGB());
			Gui.drawRect((GuiScreen.width/1.8f - 4 ), (GuiScreen.height/1.5f - 2), (GuiScreen.width/1.8f - 3), (GuiScreen.height/1.5f)+37, color);
			if(MiniTarget.isEnabled()){
				GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
				GuiInventory.drawEntityOnScreen((int)(GuiScreen.width/1.8f - 5 - 20), (int)(GuiScreen.height/1.5f)+38, 19, 1f, 1f, target);
			}
			
			
			fr.func_175063_a(target.getName(), (GuiScreen.width/1.8f), (GuiScreen.height/1.5f), -1);
			fr.func_175063_a(" HP: " + (int)target.getHealth() + " HurtTime: " + target.hurtTime, (GuiScreen.width/1.8f - 4.5f), (GuiScreen.height/1.5f + fr.FONT_HEIGHT + 2), -1);
			if(mc.thePlayer.getHealth() > target.getHealth())
			{
				fr.func_175063_a(" Winning ", (GuiScreen.width/1.8f - 4.5f), (GuiScreen.height/1.5f + fr.FONT_HEIGHT + 2 + 10), 0x1fff4e);
			}else if (mc.thePlayer.getHealth() < target.getHealth())
			{
				if((target.getHealth() - mc.thePlayer.getHealth()) < 17)
				{
					fr.func_175063_a(" Losing ", (GuiScreen.width/1.8f - 4.5f), (GuiScreen.height/1.5f + fr.FONT_HEIGHT + 2 + 10), 0xff1f1f);
				}
				
				if((target.getHealth() - mc.thePlayer.getHealth()) > 17)
				{
					fr.func_175063_a(" RUN RUN RUN ", (GuiScreen.width/1.8f - 4.5f), (GuiScreen.height/1.5f + fr.FONT_HEIGHT + 2 + 10), 0xff1f1f);
				}
			}else if (mc.thePlayer.getHealth() == target.getHealth())
			{
				fr.func_175063_a(" 50/50 ", (GuiScreen.width/1.8f - 4.5f), (GuiScreen.height/1.5f + fr.FONT_HEIGHT + 2 + 10), 0x1fff4e);
			}
			
			

			
			Gui.drawRect((GuiScreen.width/1.8f - 5 - offset), (GuiScreen.height/1.5f)+38, (GuiScreen.width/1.8f - 5 - offset) + ((125+offset) *(target.getHealth() / target.getMaxHealth())), (GuiScreen.height/1.5f)+40, color); 
			/
Thats my own targethud. Client made from Intent tutorial so should work on ur client
i made another if (e instanceof EventRenderGUI) to not get a crash and another thing with sorting targets but now sorted "range.getValue() + 3" to get targethud before hitting the player
The offset value is disabling or enabling the miniplayer (like in inventory but here target and same as in novoline)
https://cdn.discordapp.com/attachments/765519307106025484/767311067654258688/Editor23.mp4  feel free to copy. my completly own targethud. If u wanna add it as style option to targethud

**Comment by l1ving** [comment]
> Thats my own targethud

I HIGHLY doubt you wrote decompiled code :sick:

**Comment by Floofy-Fox** [comment]
Added wtap and criticals

**Comment by KtntKot** [comment]
> > Thats my own targethud
> 
> I HIGHLY doubt you wrote decompiled code :sick:

okay FIND IT FIND SAME TARGETHUD
ik that this can mean nothing but just look 2 days ago. if u wanna find my discord and see this live sure Youtube: KtntKot
![image](https://user-images.githubusercontent.com/72389680/96479327-16ce8080-1239-11eb-8236-7fa4849e2767.png)

**Comment by l1ving** [comment]
It doesn't make sense that you would write decompiled code. I literally can't think of a valid reason why you'd do that if it's your code.

**Comment by KtntKot** [comment]
> It doesn't make sense that you would write decompiled code. I literally can't think of a valid reason why you'd do that if it's your code.

i like the devs of this client lol

**Comment by NathanKassab** [comment]
Thank you KtntKot, your code was added to the client

**Comment by Floofy-Fox** [comment]
50% of these were completed, therefor I will close this
