### ISSUE TITLE
[CRITICAL] Site Down?

### ISSUE THREAD

**Issue by Agentkempo** [NathanKassab/SpicyClient#6]

**Comment by l1ving** [comment]
It's not down, it's suspended.

**Comment by NathanKassab** [comment]
Everyone using titannodes webhosting has their account suspended. I am trying to get the site back up but I don't think support will respond until monday

**Comment by l1ving** [comment]
Well you're using MCP. I'm pretty sure I suggested before to not use MCP, as you're illegally distributing Minecraft's decompiled code. I recommend using Forge for 1.12.2, or Fabric for anything newer.

**Comment by NathanKassab** [comment]
I used MCP because it allows me to give out a single jar file that requires significantly less work to install

**Comment by l1ving** [comment]
It's still illegal.

**Comment by l1ving** [comment]
Forge is also a single jar file. My mod has an installer which is like 50 lines of code and moves it to the mods folder for you...

**Comment by KtntKot** [comment]
> Forge is also a single jar file. My mod has an installer which is like 50 lines of code and moves it to the mods folder for you...

yes but still
>5 mins downloading
>2 minuts installing forge
>Getting into forge to get mods folder(or manual) ~2min
>longer loading time

**Comment by l1ving** [comment]
You only need to install Forge one time. 

> 5 mins downloading

You still need to download SpicyClient somehow???

> Getting into forge to get mods folder(or manual) ~2min

You still need to drag SpicyClient to a versions folder so I don't understand your argument 

>  longer loading time

Get a better computer. It's much cheaper then being sued for illegally distributing Minecraft's decompiled code.

**Comment by NathanKassab** [comment]
I'm going to close the issue now due to the problem being explained and there also seems to be a fight going on in it
