### ISSUE TITLE
More things to add

### ISSUE THREAD

**Issue by Floofy-Fox** [NathanKassab/SpicyClient#7]
anti lava : places water on any lava you step in so you don't get stuck or burn
auto clutch : mlg blocks for you

**Comment by NathanKassab** [comment]
kind of added anti lava, the only issues are that it does not check what type of bucket it uses to pick it up and it only checks the hotbar. All I need to do is check all the buckets and select the best one, the ranking would be water to empty to lava

**Comment by NathanKassab** [comment]
Added basic antilava, might add autoclutch later
